// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.9.0
// source: etf/v1/etf.proto

package etf

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetEtfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEtfRequest) Reset() {
	*x = GetEtfRequest{}
	mi := &file_etf_v1_etf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtfRequest) ProtoMessage() {}

func (x *GetEtfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etf_v1_etf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtfRequest.ProtoReflect.Descriptor instead.
func (*GetEtfRequest) Descriptor() ([]byte, []int) {
	return file_etf_v1_etf_proto_rawDescGZIP(), []int{0}
}

func (x *GetEtfRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetEtfReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	TenYCagr      float64                `protobuf:"fixed64,3,opt,name=ten_y_cagr,json=tenYCagr,proto3" json:"ten_y_cagr,omitempty"` //近十年年化收益率 double精度达15位，float精度只有7位
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEtfReply) Reset() {
	*x = GetEtfReply{}
	mi := &file_etf_v1_etf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEtfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEtfReply) ProtoMessage() {}

func (x *GetEtfReply) ProtoReflect() protoreflect.Message {
	mi := &file_etf_v1_etf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEtfReply.ProtoReflect.Descriptor instead.
func (*GetEtfReply) Descriptor() ([]byte, []int) {
	return file_etf_v1_etf_proto_rawDescGZIP(), []int{1}
}

func (x *GetEtfReply) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetEtfReply) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetEtfReply) GetTenYCagr() float64 {
	if x != nil {
		return x.TenYCagr
	}
	return 0
}

type CreateEtfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEtfRequest) Reset() {
	*x = CreateEtfRequest{}
	mi := &file_etf_v1_etf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEtfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEtfRequest) ProtoMessage() {}

func (x *CreateEtfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etf_v1_etf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEtfRequest.ProtoReflect.Descriptor instead.
func (*CreateEtfRequest) Descriptor() ([]byte, []int) {
	return file_etf_v1_etf_proto_rawDescGZIP(), []int{2}
}

type CreateEtfReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEtfReply) Reset() {
	*x = CreateEtfReply{}
	mi := &file_etf_v1_etf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEtfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEtfReply) ProtoMessage() {}

func (x *CreateEtfReply) ProtoReflect() protoreflect.Message {
	mi := &file_etf_v1_etf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEtfReply.ProtoReflect.Descriptor instead.
func (*CreateEtfReply) Descriptor() ([]byte, []int) {
	return file_etf_v1_etf_proto_rawDescGZIP(), []int{3}
}

type UpdateEtfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEtfRequest) Reset() {
	*x = UpdateEtfRequest{}
	mi := &file_etf_v1_etf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEtfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEtfRequest) ProtoMessage() {}

func (x *UpdateEtfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etf_v1_etf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEtfRequest.ProtoReflect.Descriptor instead.
func (*UpdateEtfRequest) Descriptor() ([]byte, []int) {
	return file_etf_v1_etf_proto_rawDescGZIP(), []int{4}
}

type UpdateEtfReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEtfReply) Reset() {
	*x = UpdateEtfReply{}
	mi := &file_etf_v1_etf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEtfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEtfReply) ProtoMessage() {}

func (x *UpdateEtfReply) ProtoReflect() protoreflect.Message {
	mi := &file_etf_v1_etf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEtfReply.ProtoReflect.Descriptor instead.
func (*UpdateEtfReply) Descriptor() ([]byte, []int) {
	return file_etf_v1_etf_proto_rawDescGZIP(), []int{5}
}

type DeleteEtfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEtfRequest) Reset() {
	*x = DeleteEtfRequest{}
	mi := &file_etf_v1_etf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEtfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEtfRequest) ProtoMessage() {}

func (x *DeleteEtfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etf_v1_etf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEtfRequest.ProtoReflect.Descriptor instead.
func (*DeleteEtfRequest) Descriptor() ([]byte, []int) {
	return file_etf_v1_etf_proto_rawDescGZIP(), []int{6}
}

type DeleteEtfReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteEtfReply) Reset() {
	*x = DeleteEtfReply{}
	mi := &file_etf_v1_etf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteEtfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteEtfReply) ProtoMessage() {}

func (x *DeleteEtfReply) ProtoReflect() protoreflect.Message {
	mi := &file_etf_v1_etf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteEtfReply.ProtoReflect.Descriptor instead.
func (*DeleteEtfReply) Descriptor() ([]byte, []int) {
	return file_etf_v1_etf_proto_rawDescGZIP(), []int{7}
}

type ListEtfRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEtfRequest) Reset() {
	*x = ListEtfRequest{}
	mi := &file_etf_v1_etf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEtfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEtfRequest) ProtoMessage() {}

func (x *ListEtfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_etf_v1_etf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEtfRequest.ProtoReflect.Descriptor instead.
func (*ListEtfRequest) Descriptor() ([]byte, []int) {
	return file_etf_v1_etf_proto_rawDescGZIP(), []int{8}
}

type ListEtfReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEtfReply) Reset() {
	*x = ListEtfReply{}
	mi := &file_etf_v1_etf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEtfReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEtfReply) ProtoMessage() {}

func (x *ListEtfReply) ProtoReflect() protoreflect.Message {
	mi := &file_etf_v1_etf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEtfReply.ProtoReflect.Descriptor instead.
func (*ListEtfReply) Descriptor() ([]byte, []int) {
	return file_etf_v1_etf_proto_rawDescGZIP(), []int{9}
}

var File_etf_v1_etf_proto protoreflect.FileDescriptor

const file_etf_v1_etf_proto_rawDesc = "" +
	"\n" +
	"\x10etf/v1/etf.proto\x12\n" +
	"api.etf.v1\x1a\x1cgoogle/api/annotations.proto\"\x1f\n" +
	"\rGetEtfRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"O\n" +
	"\vGetEtfReply\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1c\n" +
	"\n" +
	"ten_y_cagr\x18\x03 \x01(\x01R\btenYCagr\"\x12\n" +
	"\x10CreateEtfRequest\"\x10\n" +
	"\x0eCreateEtfReply\"\x12\n" +
	"\x10UpdateEtfRequest\"\x10\n" +
	"\x0eUpdateEtfReply\"\x12\n" +
	"\x10DeleteEtfRequest\"\x10\n" +
	"\x0eDeleteEtfReply\"\x10\n" +
	"\x0eListEtfRequest\"\x0e\n" +
	"\fListEtfReply2\xec\x02\n" +
	"\x03Etf\x12E\n" +
	"\tCreateEtf\x12\x1c.api.etf.v1.CreateEtfRequest\x1a\x1a.api.etf.v1.CreateEtfReply\x12E\n" +
	"\tUpdateEtf\x12\x1c.api.etf.v1.UpdateEtfRequest\x1a\x1a.api.etf.v1.UpdateEtfReply\x12E\n" +
	"\tDeleteEtf\x12\x1c.api.etf.v1.DeleteEtfRequest\x1a\x1a.api.etf.v1.DeleteEtfReply\x12?\n" +
	"\aListEtf\x12\x1a.api.etf.v1.ListEtfRequest\x1a\x18.api.etf.v1.ListEtfReply\x12O\n" +
	"\x06GetEtf\x12\x19.api.etf.v1.GetEtfRequest\x1a\x17.api.etf.v1.GetEtfReply\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/etf/{id}BR\n" +
	"\n" +
	"api.etf.v1B\bEtfProtoP\x01Z8github.com/wegge0857/PolyrepoGoMicros-ApiLink/etf/v1;etfb\x06proto3"

var (
	file_etf_v1_etf_proto_rawDescOnce sync.Once
	file_etf_v1_etf_proto_rawDescData []byte
)

func file_etf_v1_etf_proto_rawDescGZIP() []byte {
	file_etf_v1_etf_proto_rawDescOnce.Do(func() {
		file_etf_v1_etf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_etf_v1_etf_proto_rawDesc), len(file_etf_v1_etf_proto_rawDesc)))
	})
	return file_etf_v1_etf_proto_rawDescData
}

var file_etf_v1_etf_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_etf_v1_etf_proto_goTypes = []any{
	(*GetEtfRequest)(nil),    // 0: api.etf.v1.GetEtfRequest
	(*GetEtfReply)(nil),      // 1: api.etf.v1.GetEtfReply
	(*CreateEtfRequest)(nil), // 2: api.etf.v1.CreateEtfRequest
	(*CreateEtfReply)(nil),   // 3: api.etf.v1.CreateEtfReply
	(*UpdateEtfRequest)(nil), // 4: api.etf.v1.UpdateEtfRequest
	(*UpdateEtfReply)(nil),   // 5: api.etf.v1.UpdateEtfReply
	(*DeleteEtfRequest)(nil), // 6: api.etf.v1.DeleteEtfRequest
	(*DeleteEtfReply)(nil),   // 7: api.etf.v1.DeleteEtfReply
	(*ListEtfRequest)(nil),   // 8: api.etf.v1.ListEtfRequest
	(*ListEtfReply)(nil),     // 9: api.etf.v1.ListEtfReply
}
var file_etf_v1_etf_proto_depIdxs = []int32{
	2, // 0: api.etf.v1.Etf.CreateEtf:input_type -> api.etf.v1.CreateEtfRequest
	4, // 1: api.etf.v1.Etf.UpdateEtf:input_type -> api.etf.v1.UpdateEtfRequest
	6, // 2: api.etf.v1.Etf.DeleteEtf:input_type -> api.etf.v1.DeleteEtfRequest
	8, // 3: api.etf.v1.Etf.ListEtf:input_type -> api.etf.v1.ListEtfRequest
	0, // 4: api.etf.v1.Etf.GetEtf:input_type -> api.etf.v1.GetEtfRequest
	3, // 5: api.etf.v1.Etf.CreateEtf:output_type -> api.etf.v1.CreateEtfReply
	5, // 6: api.etf.v1.Etf.UpdateEtf:output_type -> api.etf.v1.UpdateEtfReply
	7, // 7: api.etf.v1.Etf.DeleteEtf:output_type -> api.etf.v1.DeleteEtfReply
	9, // 8: api.etf.v1.Etf.ListEtf:output_type -> api.etf.v1.ListEtfReply
	1, // 9: api.etf.v1.Etf.GetEtf:output_type -> api.etf.v1.GetEtfReply
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_etf_v1_etf_proto_init() }
func file_etf_v1_etf_proto_init() {
	if File_etf_v1_etf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_etf_v1_etf_proto_rawDesc), len(file_etf_v1_etf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_etf_v1_etf_proto_goTypes,
		DependencyIndexes: file_etf_v1_etf_proto_depIdxs,
		MessageInfos:      file_etf_v1_etf_proto_msgTypes,
	}.Build()
	File_etf_v1_etf_proto = out.File
	file_etf_v1_etf_proto_goTypes = nil
	file_etf_v1_etf_proto_depIdxs = nil
}
