// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.9.0
// source: etf/v1/etf.proto

package etf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Etf_CreateEtf_FullMethodName = "/api.etf.v1.Etf/CreateEtf"
	Etf_UpdateEtf_FullMethodName = "/api.etf.v1.Etf/UpdateEtf"
	Etf_DeleteEtf_FullMethodName = "/api.etf.v1.Etf/DeleteEtf"
	Etf_ListEtf_FullMethodName   = "/api.etf.v1.Etf/ListEtf"
	Etf_GetEtf_FullMethodName    = "/api.etf.v1.Etf/GetEtf"
)

// EtfClient is the client API for Etf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EtfClient interface {
	CreateEtf(ctx context.Context, in *CreateEtfRequest, opts ...grpc.CallOption) (*CreateEtfReply, error)
	UpdateEtf(ctx context.Context, in *UpdateEtfRequest, opts ...grpc.CallOption) (*UpdateEtfReply, error)
	DeleteEtf(ctx context.Context, in *DeleteEtfRequest, opts ...grpc.CallOption) (*DeleteEtfReply, error)
	ListEtf(ctx context.Context, in *ListEtfRequest, opts ...grpc.CallOption) (*ListEtfReply, error)
	GetEtf(ctx context.Context, in *GetEtfRequest, opts ...grpc.CallOption) (*GetEtfReply, error)
}

type etfClient struct {
	cc grpc.ClientConnInterface
}

func NewEtfClient(cc grpc.ClientConnInterface) EtfClient {
	return &etfClient{cc}
}

func (c *etfClient) CreateEtf(ctx context.Context, in *CreateEtfRequest, opts ...grpc.CallOption) (*CreateEtfReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEtfReply)
	err := c.cc.Invoke(ctx, Etf_CreateEtf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etfClient) UpdateEtf(ctx context.Context, in *UpdateEtfRequest, opts ...grpc.CallOption) (*UpdateEtfReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEtfReply)
	err := c.cc.Invoke(ctx, Etf_UpdateEtf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etfClient) DeleteEtf(ctx context.Context, in *DeleteEtfRequest, opts ...grpc.CallOption) (*DeleteEtfReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEtfReply)
	err := c.cc.Invoke(ctx, Etf_DeleteEtf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etfClient) ListEtf(ctx context.Context, in *ListEtfRequest, opts ...grpc.CallOption) (*ListEtfReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEtfReply)
	err := c.cc.Invoke(ctx, Etf_ListEtf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etfClient) GetEtf(ctx context.Context, in *GetEtfRequest, opts ...grpc.CallOption) (*GetEtfReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEtfReply)
	err := c.cc.Invoke(ctx, Etf_GetEtf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EtfServer is the server API for Etf service.
// All implementations must embed UnimplementedEtfServer
// for forward compatibility.
type EtfServer interface {
	CreateEtf(context.Context, *CreateEtfRequest) (*CreateEtfReply, error)
	UpdateEtf(context.Context, *UpdateEtfRequest) (*UpdateEtfReply, error)
	DeleteEtf(context.Context, *DeleteEtfRequest) (*DeleteEtfReply, error)
	ListEtf(context.Context, *ListEtfRequest) (*ListEtfReply, error)
	GetEtf(context.Context, *GetEtfRequest) (*GetEtfReply, error)
	mustEmbedUnimplementedEtfServer()
}

// UnimplementedEtfServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEtfServer struct{}

func (UnimplementedEtfServer) CreateEtf(context.Context, *CreateEtfRequest) (*CreateEtfReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateEtf not implemented")
}
func (UnimplementedEtfServer) UpdateEtf(context.Context, *UpdateEtfRequest) (*UpdateEtfReply, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEtf not implemented")
}
func (UnimplementedEtfServer) DeleteEtf(context.Context, *DeleteEtfRequest) (*DeleteEtfReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteEtf not implemented")
}
func (UnimplementedEtfServer) ListEtf(context.Context, *ListEtfRequest) (*ListEtfReply, error) {
	return nil, status.Error(codes.Unimplemented, "method ListEtf not implemented")
}
func (UnimplementedEtfServer) GetEtf(context.Context, *GetEtfRequest) (*GetEtfReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEtf not implemented")
}
func (UnimplementedEtfServer) mustEmbedUnimplementedEtfServer() {}
func (UnimplementedEtfServer) testEmbeddedByValue()             {}

// UnsafeEtfServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EtfServer will
// result in compilation errors.
type UnsafeEtfServer interface {
	mustEmbedUnimplementedEtfServer()
}

func RegisterEtfServer(s grpc.ServiceRegistrar, srv EtfServer) {
	// If the following call panics, it indicates UnimplementedEtfServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Etf_ServiceDesc, srv)
}

func _Etf_CreateEtf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEtfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtfServer).CreateEtf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Etf_CreateEtf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtfServer).CreateEtf(ctx, req.(*CreateEtfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etf_UpdateEtf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEtfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtfServer).UpdateEtf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Etf_UpdateEtf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtfServer).UpdateEtf(ctx, req.(*UpdateEtfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etf_DeleteEtf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEtfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtfServer).DeleteEtf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Etf_DeleteEtf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtfServer).DeleteEtf(ctx, req.(*DeleteEtfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etf_ListEtf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEtfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtfServer).ListEtf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Etf_ListEtf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtfServer).ListEtf(ctx, req.(*ListEtfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Etf_GetEtf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEtfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtfServer).GetEtf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Etf_GetEtf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtfServer).GetEtf(ctx, req.(*GetEtfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Etf_ServiceDesc is the grpc.ServiceDesc for Etf service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Etf_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.etf.v1.Etf",
	HandlerType: (*EtfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEtf",
			Handler:    _Etf_CreateEtf_Handler,
		},
		{
			MethodName: "UpdateEtf",
			Handler:    _Etf_UpdateEtf_Handler,
		},
		{
			MethodName: "DeleteEtf",
			Handler:    _Etf_DeleteEtf_Handler,
		},
		{
			MethodName: "ListEtf",
			Handler:    _Etf_ListEtf_Handler,
		},
		{
			MethodName: "GetEtf",
			Handler:    _Etf_GetEtf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "etf/v1/etf.proto",
}
